### ISSUE TITLE
Problem publishing in Azure Web site with Azure DB

### ISSUE THREAD

**Issue by jomague46** [OfficeDev/O365-WebApp-SingleTenant#3]
I am facing strange issue, I'm following this sample. I follow all steps and Works succesfully in localhost  but when I deploy the same app on Microsoft Azure, it throws the following exception Failed to acquire token silently. Call method AcquireToken. My code runs perfectly against localhost but not on azure. In both cases the App connects to database without problems but there is problems with ADALTokenCache in a Azure Web Site.

I would need steps to publish this sample or similar in a Azure Website and Azure DB.  Is possible?

Others samples like O365-ASPNETMVC-Start or O365-WebApp-MultiTenant have the same problem. 

<img width="763" alt="error" src="https://cloud.githubusercontent.com/assets/11057364/10307033/9347060a-6c2b-11e5-8715-3b0cd90693f6.PNG">

**Comment by jomague46** [comment]
<img width="763" alt="error" src="https://cloud.githubusercontent.com/assets/11057364/10306462/715632d6-6c27-11e5-83b8-695639773011.PNG">

**Comment by HA1311** [comment]
by any chance did you get this fix ? i'm also facing same issue ! 
in my case browser shows plain white page... with tab title "working.."

**Comment by davidchesnut** [comment]
Closing all issues since this repo is being archived and no longer maintained.
