### ISSUE TITLE
Web.config values

### ISSUE THREAD

**Issue by koti234** [OfficeDev/O365-WebApp-SingleTenant#4]
Hi Anyone,

Please tell where I can get the fallowing value in web.cong
1)ida:TenantId
2)ida:ClientId
3)ida:ClientSecret
4)ida:AADInstance

<add key="ida:TenantId" value="45e4e408-38e2-4546-bfb0-31f2b5bb41ef" />
 <add key="ida:ClientId" value="6ba825ca-d274-4fae-8681-ecf6fedbdd61" />
 <add key="ida:ClientSecret" value="6HpEZxfbbk1RM7nH8iSD0TnTPYtOpBMhoLxdu9z27+o=" />
 <add key="ida:AADInstance" value="https://login.microsoftonline.com/" />

Regards,
Kotireddy.

**Comment by davidchesnut** [comment]
Closing all issues since this repo is being archived and no longer maintained.
